#Patch DS idrepo
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ds-idrepo
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: ds
          image: ghcr.io/maximv93/ds-idrepo:v1 
          resources:
            requests:
              memory: 1Gi
              cpu: 500m
            limits:
              memory: 1Gi
      initContainers:
      - name: initialize
        image: ghcr.io/maximv93/ds-idrepo:v1 
        resources:
          requests:
            memory: 1Gi
            cpu: 500m
          limits:
            memory: 1Gi
      imagePullSecrets:
        - name: githubpullsecret            
  volumeClaimTemplates:
  - metadata:
      name: data
      annotations:
        pv.beta.kubernetes.io/gid: "0"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
      storageClassName: fast